---
- hosts: all
  gather_facts: no
  become: yes
  roles:
    - bash_tuning
    - sysstat_tuning

- hosts: compute
  gather_facts: no
  become: yes
  roles:
    - aggregation_tuning
    - max_fixed_ips_tuning-compute

- hosts: controller
  gather_facts: no
  become: yes
  roles:
    - max_fixed_ips_tuning-controller
